CREATE TABLE sleep_log(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_sleep TIMESTAMP,
    time_in_bed INT,
    time_to_bed TIMESTAMP,
    time_out_of_bed TIMESTAMP,
    user_felt VARCHAR
)